-- Drop and recreate kitchen_inventory table
DROP TABLE IF EXISTS kitchen_inventory;
CREATE TABLE kitchen_inventory (
    ingredient VARCHAR(100) PRIMARY KEY,
    available_amount FLOAT,
    unit VARCHAR(20)
);

-- Insert pancake ingredients with random amounts
INSERT INTO kitchen_inventory (ingredient, available_amount, unit) VALUES
    ('all-purpose flour', 25.5, 'kg'),
    ('whole wheat flour', 15.2, 'kg'),
    ('baking powder', 2.3, 'kg'),
    ('baking soda', 1.5, 'kg'),
    ('salt', 3.2, 'kg'),
    ('white sugar', 12.8, 'kg'),
    ('brown sugar', 8.4, 'kg'),
    ('egg', 3.4, 'kg'),
    ('butter', 8.5, 'kg'),
    ('vegetable oil', 12.3, 'l'),
    ('vanilla extract', 1.2, 'l'),
    ('cinnamon', 1.8, 'kg'),
    ('nutmeg', 0.8, 'kg'),
    ('blueberries', 4.5, 'kg'),
    ('strawberries', 3.2, 'kg'),
    ('bananas', 6.8, 'kg'),
    ('apples', 5.4, 'kg'),
    ('chocolate chips', 3.6, 'kg'),
    ('maple syrup', 8.2, 'l'),
    ('honey', 4.5, 'l'),
    ('whipped cream', 5.2, 'l'),
    ('yogurt', 12.5, 'l'),
    ('sour cream', 4.8, 'l'),
    ('cream cheese', 3.2, 'kg'),
    ('pecans', 2.8, 'kg'),
    ('walnuts', 2.5, 'kg'),
    ('almonds', 3.1, 'kg'),
    ('raisins', 2.2, 'kg'),
    ('coconut flakes', 1.8, 'kg'),
    ('pumpkin puree', 4.2, 'kg'),
    ('carrots', 3.5, 'kg'),
    ('zucchini', 2.8, 'kg'),
    ('sweet potatoes', 4.6, 'kg'),
    ('cornmeal', 3.2, 'kg'),
    ('oatmeal', 5.4, 'kg'),
    ('almond milk', 8.5, 'l'),
    ('soy milk', 7.2, 'l'),
    ('coconut milk', 4.8, 'l'),
    ('lemon juice', 2.5, 'l'),
    ('orange juice', 5.6, 'l'),
    ('pineapple', 3.8, 'kg'),
    ('mango', 2.9, 'kg'),
    ('peaches', 3.4, 'kg'),
    ('raspberries', 2.1, 'kg'),
    ('blackberries', 1.9, 'kg'),
    ('cranberries', 2.3, 'kg'),
    ('dates', 1.7, 'kg'),
    ('figs', 1.5, 'kg'),
    ('pomegranate seeds', 1.2, 'kg'),
    ('kiwi', 2.4, 'kg'),
    ('cocoa powder', 2.1, 'kg'),
    ('peanut butter', 4.3, 'kg'),
    ('jam', 3.7, 'l'),
    ('molasses', 1.9, 'l'),
    ('cardamom', 0.6, 'kg'),
    ('ginger', 1.2, 'kg'),
    ('pumpkin spice', 0.9, 'kg'),
    ('protein powder', 2.4, 'kg'),
    ('chia seeds', 1.5, 'kg'),
    ('flax seeds', 1.8, 'kg'),
    ('agave syrup', 2.2, 'l'),
    ('caramel sauce', 1.8, 'l'),
    ('flour', 20.0, 'kg'),
    ('milk', 20.0, 'l'),
    ('sugar', 10.0, 'kg');

-- Check: Select 5 random ingredients to verify the data
SELECT * FROM kitchen_inventory ORDER BY RANDOM() LIMIT 5; 